config/routes.rb
Rails.application.routes.draw do
  get 'errors/show'
  root to: 'home#index'

  devise_for :users
  get '/dashboard' => 'dashboards#show', :as => :user_root

  resource :dashboard, only: [:show] do
    resources :notes, only: [:show, :new, :edit, :create, :update, :destroy]
  end

  resource :emails, only: [:create]

  get '*unmatched_route', to: 'errors#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/note_validations.rb
module NoteValidations
  extend ActiveSupport::Concern

  included do
    validates :body, length: { maximum: 1000 }
    validates :title, length: { maximum: 30 }
    validates :user_id, presence: true

    with_options if: -> { content_is_blank? } do |note|
      note.validates :title, presence: true
    end

    with_options if: -> { note_is_private? } do |note|
      note.validates :password, presence: true, length: { minimum: 6 }
    end

    private

    def content_is_blank?
      body.blank? && title.blank?
    end

    def note_is_private?
      # the first branch is to handle updating notes in the db
      # the second branch handles the creation of notes via the form service

      if respond_to?(:password_digest)
        is_private? && password_digest.nil?
      else
        is_private?
      end
    end

    def is_private?
      (private == true || private == "true")
    end
  end
end

app/models/note.rb
class Note < ApplicationRecord
  include NoteValidations
  before_save :assign_note_title?
  before_save :update_priority
  has_secure_password validations: false

  belongs_to :user, touch: true

  enum priority: ["Whenever", "Low", "Medium", "High", "Urgent"]

  def public?
    !private?
  end

  def urgent?
    urgency == "High" || urgency == "Urgent"
  end

  def new_email
    @new_email ||= Notes::EmailService.new
  end

  private

  def assign_note_title?
    self.title = self.body[0...30] if self.title.blank?
  end

  def update_priority
    self.priority = self.urgency
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def clear_session
    session.delete(:authenticated)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  before_action :clear_session

  layout "dashboard"

  def show
    @dashboard = Dashboard.new(current_user, params)
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
    email = Notes::EmailService.new(email_params)

    if email.deliver
      redirect_with_notice
    else
      redirect_with_errors
    end
  end

  private

  def email_params
    params.require(:notes_email_service).permit(:user_id, :note_id)
  end

  def redirect_with_notice
    flash[:notice] = "Email sent."
    redirect_back(fallback_location: root_url)
  end

  def redirect_with_errors
    flash[:alert] = "Failed to send email."
    redirect_back(fallback_location: root_url)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :clear_session

  def index
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, only: [:show, :edit]
  before_action :authenticate_password, only: [:show, :edit]

  layout "dashboard"

  def new
    @note = Note.new
  end

  def show
  end

  def edit
  end

  def create
    @note = Notes::FormService.new(note_params)

    if @note.save
      redirect_with_notice
    else
      redirect_back_with_errors
    end
  end

  def update
    if @note.update(note_params)
      redirect_with_notice
    else
      redirect_back_with_errors
    end
  end

  def destroy
    if @note.destroy
      redirect_with_notice(notice: "Note deleted.")
    else
      redirect_back_with_errors(alert: "Failed to delete the message.")
    end
  end

  private

  def set_note
    @note = Note.find_by!(id: params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to "/whoops"
  end

  def authorize_user
    if @note.user != current_user
      redirect_to "/whoops"
    end
  end

  def authenticate_password
    return if @note.public?

    if @note.authenticate(params[:password])
      session[:authenticated] = true
      redirect_back(fallback_location: root_url)
    elsif incorrect_password?
      redirect_back_with_errors(alert: "Incorrect password.")
    end
  end

  def note_params
    params.require(:note).
      permit(
        :body, :category, :password, :priority, :urgency, :private, :title, :user_id, :email
      )
  end

  def redirect_with_notice(notice: "Note saved.")
    redirect_to dashboard_url, notice: notice
  end

  def redirect_back_with_errors(alert: "Failed to save the note.")
    flash[:alert] = alert
    flash[:note_errors] = @note.errors.full_messages
    redirect_back(fallback_location: root_url)
  end

  def incorrect_password?
    params[:password] && !@note.authenticate(params[:password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    if content_for?(:title)
      "#{content_for :title} | gnoteworthy"
    else
      default_title
    end
  end

  def default_title
    "gnoteworthy | Guard the treasures of your mind"
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def urgency(note)
    if note.urgent?
      "note__urgency--red"
    end
  end

  def grid_styles
    "fas fa-th-large d-none d-md-inline-block mr-auto dashboard__view--active"
  end

  def row_styles
    "fas fa-square d-none d-md-inline-block mr-2 dashboard__view"
  end
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def sign_up_button_classes
    "button button--large button--red d-block d-sm-inline-block my-4 my-sm-0"
  end

  def log_in_button_classes
    "button button--large button--transparent d-block d-sm-inline-block ml-sm-4"
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def note_creation_info(note)
    formatted_time = note.created_at.strftime("%a %I:%M")

    "created by #{current_user.name}, #{formatted_time}"
  end
end

app/views/application/_footer.html.slim
footer.footer.mt-auto
  .d-sm-flex.justify-content-between.container
    p.m-0.footer__slogan Do something gnoteworthy
    p.m-0 &copy; 2020 gnoteworthy

app/views/application/_header.html.slim
header.header
  .container
    nav.header__nav
      ul.header__list
        li.header__item.mr-auto
          = link_to "gnoteworthy", root_path, class: "header__brand"

        - if user_signed_in?
          li.header__item
            = link_to \
              "Dashboard",
              dashboard_path,
              class: "header__dashboard"
          li.header__item
            = link_to \
              "Log out",
              destroy_user_session_path,
              method: :delete,
              class: "header__link"
        - else
          li.header__item
            = link_to "Log in", new_user_session_path, class: "header__link"
          li.header__item
            = link_to \
              "Sign up",
              new_user_registration_path,
              class: "button button--red ml-4"

app/views/dashboards/show.html.slim
= content_for :title, "Dashboard"

.dashboard.container data-controller="dashboard"
  .d-flex
    .dashboard__views
      i(
        class="#{row_styles}"
        data-action="click->dashboard#displayRow"
        data-dashboard-target="rowView"
      )
      i(
        class="#{grid_styles}"
        data-action="click->dashboard#displayGrid"
        data-dashboard-target="gridView"
      )

    .text-right.w-100
      = link_to new_dashboard_note_path, class: "button button--pink" do
        i.fas.fa-plus.dashboard__plus-icon.mr-2
        span New note

  .d-flex
    span Sort by:
    = form_tag dashboard_path, method: :get do
      = select_tag \
        "sort",
        options_for_select(\
          [["first added", :first_added],
          ["last added", :last_added],
          ["priority", :priority],
          ["title", :title],
          ["category", :category]],
          selected: params[:sort_by]),
        onchange: "this.form.submit();",
        class: "ml-1 dashboard__sort"
  .d-flex.mt-2
    span Filter by:
    = form_tag dashboard_path, method: :get do
      = select_tag \
        "filter",
        options_for_select(\
          [["Personal", :personal],
          ["TODO", :todo],
          ["Work", :work],
          ["Other", :other]],
          selected: params[:filter]),
        include_blank: "Category",
        onchange: "this.form.submit();",
        class: "ml-1 mr-3 dashboard__sort"
    = form_tag dashboard_path, method: :get do
      = select_tag \
        "filter",
        options_for_select(\
          [["Whenever", :whenever],
          ["Low", :low],
          ["Medium", :medium],
          ["High", :high],
          ["Urgent", :urgent]],
          selected: params[:filter]),
        include_blank: "Priority",
        onchange: "this.form.submit();",
        class: "ml-1 dashboard__sort"


  = render 'notes/notes', notes: @dashboard.notes

app/views/home/index.html.slim
section.hero
  .hero__about-container
    h1.hero__headline gnoteworthy
    p.hero__subheadline.ml-sm-2
      | gnoteworthy is the solution to your note-taking needs.
        Find peace knowing that we'll guard the treasures of your mind.
    - if user_signed_in?
      span.ml-sm-2
        = link_to \
          "My Dashboard",
          dashboard_path,
          class: "#{sign_up_button_classes}"
        = link_to \
          "Log out",
          destroy_user_session_path,
          method: :delete,
          class: "#{log_in_button_classes}"
    - else
      span.ml-sm-2
        = link_to \
          "Sign up",
          new_user_registration_path,
          class: "#{sign_up_button_classes}"
      span.ml-sm-2
        = link_to \
            "Log in",
            new_user_session_path,
            class: "#{log_in_button_classes}"
  .hero__learn-more-container
    span = link_to "Learn more", "#features", class: "hero__learn-more"

section.features.container
  h2.features__headline#features Features
  .row
    .col-12.col-md-4
      i.fas.fa-pen-nib.features__icon
      h3.features__subheadline Personalization
      p.mb-5.mb-md-0
        | With options to change the display and to sort your notes, you can
          have the exact look you prefer with a few clicks!


    .col-12.col-md-4
      i.fas.fa-envelope.features__icon
      h3.features__subheadline Save & send
      p.mb-5.mb-md-0
        | Take your notes with you! You can send your notes, old and new
          straight to your email.

    .col-12.col-md-4
      i.fas.fa-lock.features__icon
      h3.features__subheadline Privacy
      p
        | We take guarding your notes very seriously. You have an option to
          making a note private, so only you can have access to its contents.

section.cta
  .cta__container
    h2.cta__headline
      | Ready to do something
      span< gnoteworthy
      | ?
    - if user_signed_in?
      = link_to \
        "My dashboard",
        dashboard_path,
        class: "#{sign_up_button_classes}"
    - else
      = link_to \
        "Sign up",
        new_user_registration_path,
        class: "#{sign_up_button_classes}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title = title
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body class="d-flex flex-column #{controller_name} #{action_name}"
    = render 'header'

    - if flash.any?
      - flash.each do |key, value|
        div class="flash flash--#{key}"
          span = value.html_safe

    = yield

    = render 'footer'

app/views/layouts/dashboard.html.slim
doctype html
html
  head
    title = title
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body class="d-flex flex-column dashboard-layout #{action_name}"
    = render 'header'

    - if flash[:alert]
      div class="flash flash--alert"
        span = alert
    - if flash[:notice]
      div class="flash flash--notice"
        span = notice

    = yield

    = render 'footer'

app/views/notes/_authenticate_form.html.slim
.authenticate-form
  = form_with method: :get,  url: url, local: true do |form|
    = form.label :password, "Enter password", class: "authenticate-form__label"
    = form.password_field \
      :password,
      autofocus: true,
      placeholder: "Password",
      class: "authenticate-form__input"
    = form.submit "Submit", class: "button button--green"

app/views/notes/_form.html.slim
= content_for :title, title

.container data-controller="form"
  .form--right.mb-4
    h2.form--right__headline = title

    = form_with model: note, url: url, local: true do |form|

      - if flash[:note_errors]
        span.form--right__count = pluralize(flash[:note_errors].count, "error")

        ul.form--right__error-list
          - flash[:note_errors].each do |error|
            li.form--right__error = error

      = form.hidden_field :user_id, value: current_user.id

      .form--right__field
        = form.label :title, class: "form--right__label"
        = form.text_field \
          :title,
          autofocus: true,
          autocomplete: "off",
          data: { action: "keyup->form#updateTextCount" },
          placeholder: "Things to take care of",
          class: "form--right__input"
        small data-max="30" data-form-target="textCount" 30

      .form--right__options
        .form--right__field
          = form.label :category, class: "form--right__label text-center"
          = form.select \
            :category,
            options_for_select(\
              ["Personal", "Work", "TODO", "Other"],
              selected: note.category)

        .form--right__field
          = form.label :urgency, class: "form--right__label text-center"
          = form.select \
            :urgency,
            options_for_select(\
              ["Whenever", "Low", "Medium", "High", "Urgent"],
              selected: note.urgency)

        .form--right__field
          = form.label :private, class: "form--right__label text-center"
          = form.check_box \
            :private,
            { class: "form--right__input",
              data: { "form-target": "checkbox", action: "click->form#toggle" }},
            "true",
            "false"

        - if @note.new_record?
          .form--right__field
            = form.label :email, class: "form--right__label text-center"
            = form.check_box \
              :email,
              { class: "form--right__input" },
              "true",
              "false"

      .form--right__field.d-none.mt-4 data-form-target="field"
        = form.label :password, class: "form--right__label"
        = form.password_field \
          :password,
          autocomplete: "off",
          placeholder: "Minimum of 6 characters",
          class: "form--right__input"

      .form--right__field.mt-4
        = form.label :body, class: "form--right__label"
        = form.text_area \
          :body,
          autocomplete: "off",
          rows: 3,
          placeholder: "I need to add a new feature for customers",
          data: { action: "keyup->form#updateTextCount" },
          class: "form--right__input"
        small data-max="1000" data-form-target="textCount" 1000

      = form.submit button, class: "button button--green mt-4 mb-2"

    = link_to "Back", dashboard_path, class: "form--right__link"

app/views/notes/_notes.html.slim
.row.mt-5
  - notes.each do |note|
    .col-8.offset-2.offset-md-0.offset-lg-0.col-md-6.col-lg-3.mb-5 data-dashboard-target="note"
      .note
        .note__options
          .d-flex.align-items-center.mr-auto
            = form_with \
              model: note.new_email,
              url: emails_path,
              local: true do |form|
                = form.hidden_field :note_id, value: note.id

                = form.button \
                  "<i class='fas fa-envelope mr-1'></i> Email".html_safe,
                  class: "note__email"

          = link_to "Edit", edit_dashboard_note_path(note), class: "note__edit"
          = link_to \
            "Delete",
            dashboard_note_path(note),
            method: :delete,
            data: { "confirm": "Are you sure?" },
            class: "note__delete"

        - if note.private?
          .d-flex.justify-content-between.align-items-center
            h3 class="note__title #{urgency(note)}" = note.title
            i.fas.fa-lock
          small.d-inline-block.font-italic = note_creation_info(note)

        - if note.public?
          h3 class="note__title #{urgency(note)}" = note.title
          i.fas.fa-pen-fancy
          small.mb-3.d-inline-block.font-italic = note_creation_info(note)

          .d-flex.justify-content-between
            .d-flex.align-items-baseline
              i.fas.fa-clipboard.icon--clipboard.mr-2
              span = note.category
            .d-flex.align-items-center
              i.fas.fa-bullseye.icon--bullseye.mr-2
              span class="#{urgency(note)}" = note.urgency

          - if note.body.blank?
            p.mt-4 No additional information was provided for this note.
          - else
            p.mt-4.d-none data-body="full" = note.body
            p.mt-4 data-body="truncated"
              | #{note.body.truncate(100, omission: "... (continued)")}

        = link_to \
          "View",
          dashboard_note_path(note),
          class: "button button--green mt-4"

app/views/notes/edit.html.slim
= render 'notes/form',
  note: @note,
  title: "Edit note",
  button: "Edit note",
  url: dashboard_note_path

app/views/notes/new.html.slim
= render 'notes/form',
  note: @note,
  title: "New note",
  button: "Add note",
  url: dashboard_notes_path

app/views/notes/show.html.slim
- if @note.public? || session[:authenticated]
  .container.form
    .form--left.d-none.d-md-flex.flex-md-column
      .mb-1.text-right
        = form_with \
          model: @note.new_email,
          url: emails_path,
          local: true do |form|
            = form.hidden_field :note_id, value: @note.id

            = form.button \
              "<i class='fas fa-envelope mr-1'></i> Email".html_safe,
              class: "note__email"

      i.far.fa-lightbulb.form--left__lightbulb
      h3.form--left__headline.mt-2.mb-4 = @note.title

      .d-flex.align-items-center.mb-2
        i.fas.fa-clipboard-list.form--left__clipboard.mr-2
        span = @note.category

      .d-flex.align-items-center
        i.fas.fa-bullseye.form--left__bullseye.mr-2
        span = @note.urgency

    .form--right
      .d-flex.mb-3.align-items-center
        i.fas.fa-pen-fancy.mr-1
        small.mr-auto.d-inline-block = note_creation_info(@note)
        = link_to "Edit", edit_dashboard_note_path(@note), class: "note__edit"
        = link_to \
          "Delete",
          dashboard_note_path(@note),
          method: :delete,
          class: "ml-3 note__delete"

      .d-flex.d-md-none.justify-content-center.align-items-baseline
        i.far.fa-lightbulb.mr-3
        h3.font-italic = @note.title

      .d-flex.justify-content-between.mb-5.mb-md-0
        small.d-md-none.form--right__small = @note.category
        small.d-md-none.form--right__small = @note.urgency

      .form--right__body
        - if @note.body.blank?
          p.mt-md-4 No additional information was provided for this note.
        - else
          p.mt-md-4 = @note.body

        = link_to "Back", dashboard_path, class: "mt-auto mr-0 note__view"
- else
  = render "authenticate_form", url: dashboard_note_path(@note)